apiVersion: apps/v1
kind: Deployment
metadata:
  name: First_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellow_world_page
  template:
    metadata:
      labels:
        app: hellow_world_page
    spec:
      containers:
      - name: my-container
        image: 014498662890.dkr.ecr.us-east-1.amazonaws.com/web_services:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hellow_world_page
